# Exported from Render on 2025-04-29T23:19:47Z
services:
- type: web
  name: PracticaEsp32
  runtime: python
  repo: https://github.com/Ivan-Marin-00/PracticaEsp32
  plan: free
  envVars:
  - key: MONGO_URI
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
version: "1"
